version: '3.8'

services:


  db:
    image: postgres:18
    container_name: e-fatoora-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - e-fatoora-network



  auth-service:
    build: ./Auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/authdb
    depends_on:
      - db
    networks:
      - e-fatoora-network

  user-service:
    build: ./User-service
    container_name: user-service
    restart: always
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/userdb
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      - db
      - auth-service
    networks:
      - e-fatoora-network

  client-service:
    build: ./Client-service
    container_name: client-service
    restart: always
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/clientdb
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      - db
      - auth-service
    networks:
      - e-fatoora-network

  produit-service:
    build: ./Produit-service
    container_name: produit-service
    restart: always
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/produitdb
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      - db
      - auth-service
    networks:
      - e-fatoora-network

  ventes-service:
    build: ./Ventes-service
    container_name: ventes-service
    restart: always
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/ventesdb
      - AUTH_SERVICE_URL=http://auth-service:8001
      - CLIENT_SERVICE_URL=http://client-service:8003
      - PRODUIT_SERVICE_URL=http://produit-service:8004
    depends_on:
      - db
      - auth-service
      - client-service
      - produit-service
    networks:
      - e-fatoora-network

  facture-service:
    build: ./Facture-service
    container_name: facture-service
    restart: always
    ports:
      - "8006:8006"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/facturedb
      - AUTH_SERVICE_URL=http://auth-service:8001
      - CLIENT_SERVICE_URL=http://client-service:8003
      - PRODUIT_SERVICE_URL=http://produit-service:8004
      - VENTES_SERVICE_URL=http://ventes-service:8005
    depends_on:
      - db
      - auth-service
      - client-service
    networks:
      - e-fatoora-network

  notification-service:
    build: ./Notification-service
    container_name: notification-service
    restart: always
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/notificationdb
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      - db
      - auth-service
    networks:
      - e-fatoora-network

  achats-service:
    build: ./Achats-service
    container_name: achats-service
    restart: always
    ports:
      - "8008:8008"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/achatsdb
      - AUTH_SERVICE_URL=http://auth-service:8001
      - CLIENT_SERVICE_URL=http://client-service:8003
      - PRODUIT_SERVICE_URL=http://produit-service:8004
      - ENTREPRISE_SERVICE_URL=http://entreprise-service:8080
    depends_on:
      - db
      - auth-service
    networks:
      - e-fatoora-network

  entreprise-service:
    build: ./Entreprise-service
    container_name: entreprise-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/entreprisedb
      - AUTH_SERVICE_URL=http://auth-service:8001
    depends_on:
      - db
      - auth-service
    networks:
      - e-fatoora-network

  depenses-service:
    build: ./Depenses-service
    container_name: depenses-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/depensesdb
      - AUTH_SERVICE_URL=http://auth-service:8001
      - ENTREPRISE_SERVICE_URL=http://entreprise-service:8080
    depends_on:
      - db
      - auth-service
      - entreprise-service
    networks:
      - e-fatoora-network

 
  api-gateway:
    build: ./Api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - USER_SERVICE_URL=http://user-service:8002
      - CLIENT_SERVICE_URL=http://client-service:8003
      - PRODUIT_SERVICE_URL=http://produit-service:8004
      - VENTES_SERVICE_URL=http://ventes-service:8005
      - FACTURE_SERVICE_URL=http://facture-service:8006
      - NOTIFICATION_SERVICE_URL=http://notification-service:8007
      - ACHATS_SERVICE_URL=http://achats-service:8008
      - ENTREPRISE_SERVICE_URL=http://entreprise-service:8080
      - DEPENSES_SERVICE_URL=http://depenses-service:8081
      - GATEWAY_PORT=8000
    depends_on:
      - auth-service
      - user-service
      - client-service
      - produit-service
      - ventes-service
      - facture-service
      - notification-service
      - achats-service
      - entreprise-service
      - depenses-service
    networks:
      - e-fatoora-network


volumes:
  postgres_data:

networks:
  e-fatoora-network:
    driver: bridge